/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperRouteImport } from './routes/_super'
import { Route as EmployeeRouteImport } from './routes/_employee'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeWishlistRouteImport } from './routes/_employee.wishlist'
import { Route as EmployeeTransfersRouteImport } from './routes/_employee.transfers'
import { Route as EmployeeSettingsRouteImport } from './routes/_employee.settings'
import { Route as EmployeeReservationsRouteImport } from './routes/_employee.reservations'
import { Route as EmployeeReportsRouteImport } from './routes/_employee.reports'
import { Route as EmployeeProfileRouteImport } from './routes/_employee.profile'
import { Route as EmployeePaymentsRouteImport } from './routes/_employee.payments'
import { Route as EmployeeOrdersRouteImport } from './routes/_employee.orders'
import { Route as EmployeeNotificationsRouteImport } from './routes/_employee.notifications'
import { Route as EmployeeMyListingsRouteImport } from './routes/_employee.my-listings'
import { Route as EmployeeMessagesRouteImport } from './routes/_employee.messages'
import { Route as EmployeeMarketplaceRouteImport } from './routes/_employee.marketplace'
import { Route as EmployeeCreateListingRouteImport } from './routes/_employee.create-listing'
import { Route as SuperSuperAdminIndexRouteImport } from './routes/_super.super-admin.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as SuperSuperAdminTownshipsRouteImport } from './routes/_super.super-admin.townships'
import { Route as SuperSuperAdminSettingsRouteImport } from './routes/_super.super-admin.settings'
import { Route as SuperSuperAdminDepartmentsRouteImport } from './routes/_super.super-admin.departments'
import { Route as SuperSuperAdminAuditLogsRouteImport } from './routes/_super.super-admin.audit-logs'
import { Route as SuperSuperAdminAnalyticsRouteImport } from './routes/_super.super-admin.analytics'
import { Route as EmployeeTransfersEmpIdRouteImport } from './routes/_employee.transfers.$empId'
import { Route as EmployeeListingIdRouteImport } from './routes/_employee.listing.$id'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin.reports'
import { Route as AdminAdminProfileRouteImport } from './routes/_admin.admin.profile'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin.admin.notifications'
import { Route as AdminAdminListingsRouteImport } from './routes/_admin.admin.listings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/_super',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/_employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeWishlistRoute = EmployeeWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTransfersRoute = EmployeeTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeReservationsRoute = EmployeeReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeReportsRoute = EmployeeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePaymentsRoute = EmployeePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOrdersRoute = EmployeeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeMyListingsRoute = EmployeeMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeMessagesRoute = EmployeeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeMarketplaceRoute = EmployeeMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeCreateListingRoute = EmployeeCreateListingRouteImport.update({
  id: '/create-listing',
  path: '/create-listing',
  getParentRoute: () => EmployeeRoute,
} as any)
const SuperSuperAdminIndexRoute = SuperSuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperSuperAdminTownshipsRoute =
  SuperSuperAdminTownshipsRouteImport.update({
    id: '/super-admin/townships',
    path: '/super-admin/townships',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminSettingsRoute = SuperSuperAdminSettingsRouteImport.update({
  id: '/super-admin/settings',
  path: '/super-admin/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminDepartmentsRoute =
  SuperSuperAdminDepartmentsRouteImport.update({
    id: '/super-admin/departments',
    path: '/super-admin/departments',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminAuditLogsRoute =
  SuperSuperAdminAuditLogsRouteImport.update({
    id: '/super-admin/audit-logs',
    path: '/super-admin/audit-logs',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminAnalyticsRoute =
  SuperSuperAdminAnalyticsRouteImport.update({
    id: '/super-admin/analytics',
    path: '/super-admin/analytics',
    getParentRoute: () => SuperRoute,
  } as any)
const EmployeeTransfersEmpIdRoute = EmployeeTransfersEmpIdRouteImport.update({
  id: '/$empId',
  path: '/$empId',
  getParentRoute: () => EmployeeTransfersRoute,
} as any)
const EmployeeListingIdRoute = EmployeeListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProfileRoute = AdminAdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminListingsRoute = AdminAdminListingsRouteImport.update({
  id: '/admin/listings',
  path: '/admin/listings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-listing': typeof EmployeeCreateListingRoute
  '/marketplace': typeof EmployeeMarketplaceRoute
  '/messages': typeof EmployeeMessagesRoute
  '/my-listings': typeof EmployeeMyListingsRoute
  '/notifications': typeof EmployeeNotificationsRoute
  '/orders': typeof EmployeeOrdersRoute
  '/payments': typeof EmployeePaymentsRoute
  '/profile': typeof EmployeeProfileRoute
  '/reports': typeof EmployeeReportsRoute
  '/reservations': typeof EmployeeReservationsRoute
  '/settings': typeof EmployeeSettingsRoute
  '/transfers': typeof EmployeeTransfersRouteWithChildren
  '/wishlist': typeof EmployeeWishlistRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/listing/$id': typeof EmployeeListingIdRoute
  '/transfers/$empId': typeof EmployeeTransfersEmpIdRoute
  '/super-admin/analytics': typeof SuperSuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof SuperSuperAdminAuditLogsRoute
  '/super-admin/departments': typeof SuperSuperAdminDepartmentsRoute
  '/super-admin/settings': typeof SuperSuperAdminSettingsRoute
  '/super-admin/townships': typeof SuperSuperAdminTownshipsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/super-admin/': typeof SuperSuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-listing': typeof EmployeeCreateListingRoute
  '/marketplace': typeof EmployeeMarketplaceRoute
  '/messages': typeof EmployeeMessagesRoute
  '/my-listings': typeof EmployeeMyListingsRoute
  '/notifications': typeof EmployeeNotificationsRoute
  '/orders': typeof EmployeeOrdersRoute
  '/payments': typeof EmployeePaymentsRoute
  '/profile': typeof EmployeeProfileRoute
  '/reports': typeof EmployeeReportsRoute
  '/reservations': typeof EmployeeReservationsRoute
  '/settings': typeof EmployeeSettingsRoute
  '/transfers': typeof EmployeeTransfersRouteWithChildren
  '/wishlist': typeof EmployeeWishlistRoute
  '/admin/listings': typeof AdminAdminListingsRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/profile': typeof AdminAdminProfileRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/listing/$id': typeof EmployeeListingIdRoute
  '/transfers/$empId': typeof EmployeeTransfersEmpIdRoute
  '/super-admin/analytics': typeof SuperSuperAdminAnalyticsRoute
  '/super-admin/audit-logs': typeof SuperSuperAdminAuditLogsRoute
  '/super-admin/departments': typeof SuperSuperAdminDepartmentsRoute
  '/super-admin/settings': typeof SuperSuperAdminSettingsRoute
  '/super-admin/townships': typeof SuperSuperAdminTownshipsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/super-admin': typeof SuperSuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_employee': typeof EmployeeRouteWithChildren
  '/_super': typeof SuperRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_employee/create-listing': typeof EmployeeCreateListingRoute
  '/_employee/marketplace': typeof EmployeeMarketplaceRoute
  '/_employee/messages': typeof EmployeeMessagesRoute
  '/_employee/my-listings': typeof EmployeeMyListingsRoute
  '/_employee/notifications': typeof EmployeeNotificationsRoute
  '/_employee/orders': typeof EmployeeOrdersRoute
  '/_employee/payments': typeof EmployeePaymentsRoute
  '/_employee/profile': typeof EmployeeProfileRoute
  '/_employee/reports': typeof EmployeeReportsRoute
  '/_employee/reservations': typeof EmployeeReservationsRoute
  '/_employee/settings': typeof EmployeeSettingsRoute
  '/_employee/transfers': typeof EmployeeTransfersRouteWithChildren
  '/_employee/wishlist': typeof EmployeeWishlistRoute
  '/_admin/admin/listings': typeof AdminAdminListingsRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/profile': typeof AdminAdminProfileRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_employee/listing/$id': typeof EmployeeListingIdRoute
  '/_employee/transfers/$empId': typeof EmployeeTransfersEmpIdRoute
  '/_super/super-admin/analytics': typeof SuperSuperAdminAnalyticsRoute
  '/_super/super-admin/audit-logs': typeof SuperSuperAdminAuditLogsRoute
  '/_super/super-admin/departments': typeof SuperSuperAdminDepartmentsRoute
  '/_super/super-admin/settings': typeof SuperSuperAdminSettingsRoute
  '/_super/super-admin/townships': typeof SuperSuperAdminTownshipsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_super/super-admin/': typeof SuperSuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/create-listing'
    | '/marketplace'
    | '/messages'
    | '/my-listings'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/reservations'
    | '/settings'
    | '/transfers'
    | '/wishlist'
    | '/admin/listings'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/listing/$id'
    | '/transfers/$empId'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/departments'
    | '/super-admin/settings'
    | '/super-admin/townships'
    | '/admin/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/create-listing'
    | '/marketplace'
    | '/messages'
    | '/my-listings'
    | '/notifications'
    | '/orders'
    | '/payments'
    | '/profile'
    | '/reports'
    | '/reservations'
    | '/settings'
    | '/transfers'
    | '/wishlist'
    | '/admin/listings'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/users'
    | '/listing/$id'
    | '/transfers/$empId'
    | '/super-admin/analytics'
    | '/super-admin/audit-logs'
    | '/super-admin/departments'
    | '/super-admin/settings'
    | '/super-admin/townships'
    | '/admin'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_employee'
    | '/_super'
    | '/login'
    | '/register'
    | '/_employee/create-listing'
    | '/_employee/marketplace'
    | '/_employee/messages'
    | '/_employee/my-listings'
    | '/_employee/notifications'
    | '/_employee/orders'
    | '/_employee/payments'
    | '/_employee/profile'
    | '/_employee/reports'
    | '/_employee/reservations'
    | '/_employee/settings'
    | '/_employee/transfers'
    | '/_employee/wishlist'
    | '/_admin/admin/listings'
    | '/_admin/admin/notifications'
    | '/_admin/admin/profile'
    | '/_admin/admin/reports'
    | '/_admin/admin/users'
    | '/_employee/listing/$id'
    | '/_employee/transfers/$empId'
    | '/_super/super-admin/analytics'
    | '/_super/super-admin/audit-logs'
    | '/_super/super-admin/departments'
    | '/_super/super-admin/settings'
    | '/_super/super-admin/townships'
    | '/_admin/admin/'
    | '/_super/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super': {
      id: '/_super'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee': {
      id: '/_employee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee/wishlist': {
      id: '/_employee/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof EmployeeWishlistRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/transfers': {
      id: '/_employee/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof EmployeeTransfersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/settings': {
      id: '/_employee/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/reservations': {
      id: '/_employee/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof EmployeeReservationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/reports': {
      id: '/_employee/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof EmployeeReportsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/profile': {
      id: '/_employee/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/payments': {
      id: '/_employee/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof EmployeePaymentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/orders': {
      id: '/_employee/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof EmployeeOrdersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/notifications': {
      id: '/_employee/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/my-listings': {
      id: '/_employee/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof EmployeeMyListingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/messages': {
      id: '/_employee/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof EmployeeMessagesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/marketplace': {
      id: '/_employee/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof EmployeeMarketplaceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/create-listing': {
      id: '/_employee/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof EmployeeCreateListingRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_super/super-admin/': {
      id: '/_super/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperSuperAdminIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_super/super-admin/townships': {
      id: '/_super/super-admin/townships'
      path: '/super-admin/townships'
      fullPath: '/super-admin/townships'
      preLoaderRoute: typeof SuperSuperAdminTownshipsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/settings': {
      id: '/_super/super-admin/settings'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperSuperAdminSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/departments': {
      id: '/_super/super-admin/departments'
      path: '/super-admin/departments'
      fullPath: '/super-admin/departments'
      preLoaderRoute: typeof SuperSuperAdminDepartmentsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/audit-logs': {
      id: '/_super/super-admin/audit-logs'
      path: '/super-admin/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof SuperSuperAdminAuditLogsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/analytics': {
      id: '/_super/super-admin/analytics'
      path: '/super-admin/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperSuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_employee/transfers/$empId': {
      id: '/_employee/transfers/$empId'
      path: '/$empId'
      fullPath: '/transfers/$empId'
      preLoaderRoute: typeof EmployeeTransfersEmpIdRouteImport
      parentRoute: typeof EmployeeTransfersRoute
    }
    '/_employee/listing/$id': {
      id: '/_employee/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof EmployeeListingIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/profile': {
      id: '/_admin/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/listings': {
      id: '/_admin/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminAdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminListingsRoute: typeof AdminAdminListingsRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminProfileRoute: typeof AdminAdminProfileRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminListingsRoute: AdminAdminListingsRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminProfileRoute: AdminAdminProfileRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeTransfersRouteChildren {
  EmployeeTransfersEmpIdRoute: typeof EmployeeTransfersEmpIdRoute
}

const EmployeeTransfersRouteChildren: EmployeeTransfersRouteChildren = {
  EmployeeTransfersEmpIdRoute: EmployeeTransfersEmpIdRoute,
}

const EmployeeTransfersRouteWithChildren =
  EmployeeTransfersRoute._addFileChildren(EmployeeTransfersRouteChildren)

interface EmployeeRouteChildren {
  EmployeeCreateListingRoute: typeof EmployeeCreateListingRoute
  EmployeeMarketplaceRoute: typeof EmployeeMarketplaceRoute
  EmployeeMessagesRoute: typeof EmployeeMessagesRoute
  EmployeeMyListingsRoute: typeof EmployeeMyListingsRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeOrdersRoute: typeof EmployeeOrdersRoute
  EmployeePaymentsRoute: typeof EmployeePaymentsRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeReportsRoute: typeof EmployeeReportsRoute
  EmployeeReservationsRoute: typeof EmployeeReservationsRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeTransfersRoute: typeof EmployeeTransfersRouteWithChildren
  EmployeeWishlistRoute: typeof EmployeeWishlistRoute
  EmployeeListingIdRoute: typeof EmployeeListingIdRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeCreateListingRoute: EmployeeCreateListingRoute,
  EmployeeMarketplaceRoute: EmployeeMarketplaceRoute,
  EmployeeMessagesRoute: EmployeeMessagesRoute,
  EmployeeMyListingsRoute: EmployeeMyListingsRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeOrdersRoute: EmployeeOrdersRoute,
  EmployeePaymentsRoute: EmployeePaymentsRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeReportsRoute: EmployeeReportsRoute,
  EmployeeReservationsRoute: EmployeeReservationsRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeTransfersRoute: EmployeeTransfersRouteWithChildren,
  EmployeeWishlistRoute: EmployeeWishlistRoute,
  EmployeeListingIdRoute: EmployeeListingIdRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface SuperRouteChildren {
  SuperSuperAdminAnalyticsRoute: typeof SuperSuperAdminAnalyticsRoute
  SuperSuperAdminAuditLogsRoute: typeof SuperSuperAdminAuditLogsRoute
  SuperSuperAdminDepartmentsRoute: typeof SuperSuperAdminDepartmentsRoute
  SuperSuperAdminSettingsRoute: typeof SuperSuperAdminSettingsRoute
  SuperSuperAdminTownshipsRoute: typeof SuperSuperAdminTownshipsRoute
  SuperSuperAdminIndexRoute: typeof SuperSuperAdminIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperSuperAdminAnalyticsRoute: SuperSuperAdminAnalyticsRoute,
  SuperSuperAdminAuditLogsRoute: SuperSuperAdminAuditLogsRoute,
  SuperSuperAdminDepartmentsRoute: SuperSuperAdminDepartmentsRoute,
  SuperSuperAdminSettingsRoute: SuperSuperAdminSettingsRoute,
  SuperSuperAdminTownshipsRoute: SuperSuperAdminTownshipsRoute,
  SuperSuperAdminIndexRoute: SuperSuperAdminIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
